export const bosses = {
  Zakum: { kr: '자쿰', difficulties: ['Easy', 'Normal', 'Chaos'] },
  Horntail: { kr: '혼테일', difficulties: ['Easy', 'Normal', 'Chaos'] },
  Hilla: { kr: '힐라', difficulties: ['Normal', 'Hard'] },
  Cygnus: { kr: '시그너스', difficulties: ['Easy', 'Normal'] },
  Magnus: { kr: '매그너스', difficulties: ['Easy', 'Normal', 'Hard'] },
  'Pink Bean': { kr: '핑크빈', difficulties: ['Normal', 'Chaos'] },
  Papulatus: { kr: '파풀라투스', difficulties: ['Normal', 'Chaos'] },
  'Crimson Queen': { kr: '블러디퀸', difficulties: ['Normal', 'Chaos'] },
  'Von Bon': { kr: '반반', difficulties: ['Normal', 'Chaos'] },
  Pierre: { kr: '피에르', difficulties: ['Normal', 'Chaos'] },
  Vellum: { kr: '벨룸', difficulties: ['Normal', 'Chaos'] },
  Lotus: { kr: '스우', difficulties: ['Normal', 'Hard', 'Extreme'] },
  Damien: { kr: '데미안', difficulties: ['Normal', 'Hard'] },
  'Guardian Angel Slime': { kr: '가엔슬', difficulties: ['Normal', 'Chaos'] },
  Lucid: { kr: '루시드', difficulties: ['Easy', 'Normal', 'Hard'] },
  Will: { kr: '윌', difficulties: ['Easy', 'Normal', 'Hard'] },
  Gloom: { kr: '더스크', difficulties: ['Normal', 'Chaos'] },
  Darknell: { kr: '듄켈', difficulties: ['Normal', 'Hard'] },
  'Verus Hilla': { kr: '진힐라', difficulties: ['Normal', 'Hard'] },
  'Black Mage': { kr: '검은 마법사', difficulties: ['Hard', 'Extreme'] },
  Seren: { kr: '세렌', difficulties: ['Normal', 'Hard', 'Extreme'] },
  Kalos: { kr: '칼로스', difficulties: ['Easy', 'Normal', 'Chaos', 'Extreme'] },
  Adversary: { kr: '최초의 대적자', difficulties: ['Easy', 'Normal', 'Hard', 'Extreme'] },
  Kaling: { kr: '카링', difficulties: ['Easy', 'Normal', 'Hard', 'Extreme'] },
  'Radiant Malefic Star': { kr: '찬란한 흉성', diffculties: ['Normal', 'Hard'] },
  Limbo: { kr: '림보', difficulties: ['Normal', 'Hard'] },
  Baldrix: { kr: '발드릭스', difficulties: ['Normal', 'Hard'] },
  Jupiter: { kr: '유피테르', difficulties: ['Normal', 'Hard'] },
};
